language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      env: SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.1
      env: SYMFONY_DEPRECATIONS_HELPER=weak COVERAGE=true
    - php: hhvm
      env: SYMFONY_DEPRECATIONS_HELPER=weak
  fast_finish: true

before_install:
  - if [ "$COVERAGE" != "true" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - if [ "$COVERAGE" == "true" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
  - if [ "$COVERAGE" == "true" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
