language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - SYMFONY_PHPUNIT_VERSION="6.5"

matrix:
  fast_finish: true
  include:
      # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"
      # Test the latest stable release
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text --coverage-clover=coverage.clover"
      # Test LTS versions.
    - php: 7.4
      env: DEPENDENCIES="symfony/lts:^3"
      # Latest commit to master
    - php: 7.4
      env: STABILITY="dev"
  allow_failures:
      # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS

after_script:
  - if [ "$COVERAGE" == "true" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
