name: "Continuous Integration"

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: "baselineFile=./tests/allowed-deprecations.json"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2
        dependencies:
          - "highest"
        symfony-require:
          - ""
        include:
          # Test against lowest dependencies
          - php-version: "8.1"
            dependencies: "lowest"
          - php-version: "8.2"
            dependencies: "lowest"

          # Test against latest Symfony 5.4
          - symfony-require: "5.4.*"
            php-version: "8.1"
            dependencies: "highest"
          - symfony-require: "5.4.*"
            php-version: "8.2"
            dependencies: "highest"

          # Test against highest dependencies
          - php-version: "8.1"
            dependencies: "highest"
          - php-version: "8.2"
            dependencies: "highest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
          ini-values: "zend.assertions=1"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run checks
        run: |
          make check
