name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  phpunit:
    name: "Tests"
    runs-on: "ubuntu-latest"
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: "baselineFile=./tests/allowed-deprecations.json"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        dependencies:
          - "highest"
        symfony-require:
          - ""
        include:
          # Test against lowest dependencies
          - php-version: "7.4"
            dependencies: "lowest"
          - php-version: "8.0"
            dependencies: "lowest"
          - php-version: "8.1"
            dependencies: "lowest"

          # Test against latest Symfony 4.4
          - symfony-require: "4.4.*"
            php-version: "7.4"
            dependencies: "highest"
          - symfony-require: "4.4.*"
            php-version: "8.0"
            dependencies: "highest"
          - symfony-require: "4.4.*"
            php-version: "8.1"
            dependencies: "highest"

          # Test against latest Symfony 5.4
          - symfony-require: "5.4.*"
            php-version: "7.4"
            dependencies: "highest"
          - symfony-require: "5.4.*"
            php-version: "8.0"
            dependencies: "highest"
          - symfony-require: "5.4.*"
            php-version: "8.1"
            dependencies: "highest"

          # Test against highest dependencies
          - php-version: "7.4"
            dependencies: "highest"

          - php-version: "8.0"
            dependencies: "highest"

          - php-version: "8.1"
            dependencies: "highest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

#      - name: "Globally install symfony/flex"
#        run: "composer global require --no-progress --no-scripts --no-plugins symfony/flex"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run PHPUnit"
        run: |
          vendor/bin/simple-phpunit install
          vendor/bin/simple-phpunit --coverage-clover=coverage.xml
