name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: ${{matrix.symfony-deprecations-helper}}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        dependencies:
          - "highest"
        stability:
          - "stable"
        symfony-require:
          - ""
        symfony-deprecations-helper:
          - ""
        include:
          # Tests the lowest set of dependencies
          - dependencies: "lowest"
            stability: "stable"
            php-version: "7.1"
            symfony-deprecations-helper: "weak"

          # Test against latest Symfony 4.4 dev
          - symfony-require: "4.4.*"
            dependencies: "highest"
            php-version: "7.3"
            stability: "dev"

          # Test against latest Symfony 5.4 dev
          - symfony-require: "5.4.*"
            dependencies: "highest"
            php-version: "7.3"
            stability: "dev"

          # Test against latest Symfony 6.0 dev
          - symfony-require: "6.0.*"
            dependencies: "highest"
            php-version: "8.0"
            stability: "dev"

          - php-version: "8.0"
            dependencies: "highest"
            stability: "dev"
            symfony-deprecations-helper: "weak"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version == '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "xdebug"
          ini-values: "zend.assertions=1"

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version != '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Globally install symfony/flex"
        run: "composer global require --no-progress --no-scripts --no-plugins symfony/flex"

      - name: "Enforce using stable dependencies"
        run: "composer config minimum-stability stable"
        if: "${{ matrix.stability == 'stable' }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
